## Run locally - news data

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
def wrangle(path):
    # Load data
    df = pd.read_csv(path)

    # Convert 'date' column to datetime
    df['date'] = pd.to_datetime(df['Date'])

    # Sort data
    df = df.sort_values(by='date', ascending=True) 

    # # Filter data for the year 2024
    # df = df[df['date'].dt.year == 2024]

    # Drop columns
    df = df.drop(columns=['Date'])

    # Rename columns
    df = df.rename(columns={'CPUSAM_Close': 'CPI', 
                            '_VIXD_Close': 'VIX', 
                            '__XAU_D_Close': 'Gold', 
                            'BRT_D_Close': 'Oil', 
                            '_SPXD_Close': 'SP500'})

    # Set index
    df.set_index('date', inplace=True)

    return df

In [3]:
df = wrangle("/Users/alexzheng/Developer/GitHub/EC331-project/data/4.0/Macro.csv")

In [9]:
df

              SP500  CPI       Gold    VIX    Oil
date
2023-01-02      NaN  NaN  1823.6899    NaN  82.82
2023-01-03  3824.14  NaN  1839.4900  22.90  80.36
2023-01-04  3852.97  NaN  1854.0900  22.01  75.31
2023-01-05  3808.10  NaN  1833.1899  22.46  76.73
2023-01-06  3895.08  NaN  1865.7100  21.13  76.41
...             ...  ...        ...    ...    ...
2025-02-11  6068.50  NaN  2898.3401  16.02    NaN
2025-02-12  6051.97  NaN  2903.6599  15.89    NaN
2025-02-13  6115.07  NaN        NaN  15.10    NaN
2025-02-14  6114.63  NaN        NaN  14.77    NaN
2025-02-18  6129.58  NaN        NaN  15.35    NaN

[563 rows x 5 columns]

In [5]:
df.isna().sum()

SP500     1
CPI      32
Gold      3
VIX       1
Oil       5
dtype: int64

In [6]:
df.describe()

             SP500         CPI         Gold         VIX         Oil
count   562.000000  531.000000   560.000000  562.000000  558.000000
mean   4931.525783  309.265505  2199.662764   16.165712   81.340753
std     686.372928    5.123689   300.701043    3.208638    5.753835
min    3808.100000  299.170000  1810.810100   11.860000   70.310000
25%    4331.415000  305.691000  1950.345000   13.572500   76.452500
50%    4879.760000  308.417000  2035.937250   15.435000   81.320000
75%    5541.670000  314.540000  2443.710000   18.230000   85.435000
max    6129.580000  317.671000  2907.340100   38.570000   97.100000

In [7]:
# Save the cleaned data
df.to_csv('/Users/alexzheng/Developer/GitHub/EC331-project/data/4.0/cleaned_Macro.csv')