In [1]:
import pandas as pd

In [2]:
def wrangle(path):
    # Load data
    df = pd.read_csv(path)

    # Sort data
    df = df.sort_values(by='date', ascending=True)

    # Set index
    df.set_index('date', inplace=True)

    # Only select the 'sentiment_labels' column
    df = df[['sentiment_labels']]

    # Select data from 2018-05-15 06:00:00 to 2025-12-31
    df = df.loc['2018-05-15 06:00:00':'2025-12-31']

    return df

In [3]:
df = wrangle("/Users/alexzheng/Developer/GitHub/EC331-project/data/bitcoin_news.csv")

In [4]:
df.head(20)

                    sentiment_labels
date
2018-05-15 07:00:00         positive
2018-05-15 07:00:00          neutral
2018-05-15 08:00:00         positive
2018-05-15 10:00:00          neutral
2018-05-15 11:00:00          neutral
2018-05-15 11:00:00          neutral
2018-05-15 12:00:00          neutral
2018-05-15 14:00:00          neutral
2018-05-15 14:00:00         positive
2018-05-15 15:00:00         negative
2018-05-15 15:00:00         positive
2018-05-15 15:00:00         negative
2018-05-15 15:00:00          neutral
2018-05-15 15:00:00         positive
2018-05-15 16:00:00         positive
2018-05-15 18:00:00         positive
2018-05-15 18:00:00         positive
2018-05-15 18:00:00         positive
2018-05-15 19:00:00          neutral
2018-05-15 19:00:00         positive

In [5]:
df.isna().sum()

sentiment_labels    0
dtype: int64

In [6]:
df.describe()

       sentiment_labels
count             69108
unique                3
top            positive
freq              35452

#### Choose the majority as the sentiment label for the same date

In [7]:
# Define mapping for sentiment labels
sentiment_mapping = {'negative': -1, 'neutral': 0, 'positive': 1}

# Convert sentiment labels to numeric values
df['sentiment_score'] = df['sentiment_labels'].map(sentiment_mapping)

# Group by datetime index and take the mean sentiment score
df_cleaned = df.groupby(df.index)['sentiment_score'].mean()

# Convert Series to DataFrame
df_cleaned = df_cleaned.to_frame()

# Display cleaned DataFrame
df_cleaned.head()

                     sentiment_score
date
2018-05-15 07:00:00              0.5
2018-05-15 08:00:00              1.0
2018-05-15 10:00:00              0.0
2018-05-15 11:00:00              0.0
2018-05-15 12:00:00              0.0

In [8]:
df_cleaned.tail()

                     sentiment_score
date
2024-01-24 13:00:00         0.000000
2024-01-24 14:00:00         0.666667
2024-01-24 15:00:00        -1.000000
2024-01-24 21:00:00         1.000000
2024-01-24 22:00:00         1.000000

In [9]:
df_cleaned.to_csv("/Users/alexzheng/Developer/GitHub/EC331-project/data/bitcoin_scores.csv")