In [1]:
import pandas as pd

In [2]:
close_prices = pd.read_csv("/Users/alexzheng/Developer/GitHub/EC331-project/data/Bitcoin_data.csv",
                           index_col=0,
                           parse_dates=True)
close_prices.head()

,open,high,low,close,Volume BTC,Volume USD
date,,,,,,
2018-05-15 06:00:00,8733.86,8796.68,8707.28,8740.99,4906603.14,559.93
2018-05-15 07:00:00,8740.99,8766.00,8721.11,8739.00,2390398.89,273.58
2018-05-15 08:00:00,8739.00,8750.27,8660.53,8728.49,7986062.84,917.79
2018-05-15 09:00:00,8728.49,8754.40,8701.35,8708.32,1593991.98,182.62
2018-05-15 10:00:00,8708.32,8865.00,8695.11,8795.90,11101273.74,1260.69

In [3]:
sentiment_scores = pd.read_csv("/Users/alexzheng/Developer/GitHub/EC331-project/data/NEW_bitcoin_scores.csv",
                               index_col=0,
                               parse_dates=True)
sentiment_scores.head()

                     weighted_sentiment_score
date
2011-06-22 11:00:00                       0.0
2012-02-01 19:00:00                       0.0
2012-03-22 20:00:00                       0.0
2012-08-23 00:00:00                       0.0
2012-09-07 14:00:00                       0.0

In [4]:
sentiment_scores.tail()

                     weighted_sentiment_score
date
2024-01-24 13:00:00                  0.000000
2024-01-24 14:00:00                  0.000000
2024-01-24 15:00:00                  0.518206
2024-01-24 21:00:00                  0.508123
2024-01-24 22:00:00                  0.000000

In [5]:
# Merge price and sentiment data
df = pd.merge(close_prices, sentiment_scores, on='date', how='outer')

# Select dates within the specified range
df = df.loc['2018-05-15 07:00:00':'2024-01-24 22:00:00']

# Forward-fill missing sentiment scores
df['weighted_sentiment_score'] = df['weighted_sentiment_score'].ffill()

# Display first few rows
df.head()

,open,high,low,close,Volume BTC,Volume USD,weighted_sentiment_score
date,,,,,,,
2018-05-15 07:00:00,8740.99,8766.00,8721.11,8739.00,2390398.89,273.58,0.26349
2018-05-15 08:00:00,8739.00,8750.27,8660.53,8728.49,7986062.84,917.79,0.00000
2018-05-15 09:00:00,8728.49,8754.40,8701.35,8708.32,1593991.98,182.62,0.00000
2018-05-15 10:00:00,8708.32,8865.00,8695.11,8795.90,11101273.74,1260.69,0.00000
2018-05-15 11:00:00,8795.90,8821.19,8740.54,8760.00,2842987.30,324.11,0.00000

In [6]:
df.tail()

,open,high,low,close,Volume BTC,Volume USD,weighted_sentiment_score
date,,,,,,,
2024-01-24 18:00:00,40117.0,40137.0,39597.0,39754.0,180.499878,7.175592e+06,0.518206
2024-01-24 19:00:00,39742.0,39831.0,39617.0,39799.0,103.556046,4.121427e+06,0.518206
2024-01-24 20:00:00,39789.0,39988.0,39493.0,39506.0,203.527665,8.040564e+06,0.518206
2024-01-24 21:00:00,39525.0,39765.0,39461.0,39765.0,117.031355,4.653752e+06,0.508123
2024-01-24 22:00:00,39748.0,39881.0,39730.0,39869.0,64.776368,2.582569e+06,0.000000

In [7]:
df.describe()

,open,high,low,close,Volume BTC,Volume USD,weighted_sentiment_score
count,49936.000000,49936.000000,49936.000000,49936.000000,4.993600e+04,4.993600e+04,49936.000000
mean,22743.227033,22850.586565,22628.390846,22743.885549,1.073828e+06,2.767733e+06,0.197980
std,16270.719788,16356.844258,16177.630638,16270.876263,2.643497e+06,6.316341e+06,0.241762
min,3139.760000,3158.340000,3122.280000,3139.760000,0.000000e+00,0.000000e+00,-0.990313
25%,8343.410000,8381.157500,8310.520000,8343.410000,5.901332e+01,2.814150e+02,0.000000
50%,19371.015000,19440.965000,19287.960000,19370.220000,2.414339e+02,6.391276e+05,0.000000
75%,34756.122500,34970.000000,34548.197500,34752.035000,1.130458e+06,2.929618e+06,0.419001
max,68635.050000,69000.000000,68447.000000,68627.010000,6.857061e+07,2.582324e+08,0.850129

In [8]:
df.isna().sum()

open                        0
high                        0
low                         0
close                       0
Volume BTC                  0
Volume USD                  0
weighted_sentiment_score    0
dtype: int64

In [9]:
df.to_csv("/Users/alexzheng/Developer/GitHub/EC331-project/data/NEW_Bitcoin_data_full.csv")