In [1]:
import pandas as pd

In [2]:
close_prices = pd.read_csv("/Users/alexzheng/Developer/GitHub/EC331-project/data/3.0/Bitcoin_data.csv",
                           index_col=0,
                           parse_dates=True)
close_prices

,open,high,low,close,Volume BTC,Volume USD
date,,,,,,
2021-01-01 00:01:00,29007.31,29086.90,29007.31,29083.47,14.561951,423512.060397
2021-01-01 00:02:00,29069.80,29073.02,29028.14,29035.89,3.030301,87987.499279
2021-01-01 00:03:00,29037.68,29069.39,29019.00,29048.13,2.189621,63604.382387
2021-01-01 00:04:00,29048.13,29057.73,29035.61,29045.19,1.446538,42014.959434
2021-01-01 00:05:00,29021.86,29023.38,28982.33,28999.50,1.062360,30807.899250
...,...,...,...,...,...,...
2022-03-21 11:40:00,41245.56,41274.15,41243.31,41274.15,1.001110,41319.964306
2022-03-21 11:41:00,41274.15,41274.15,41273.33,41274.15,0.007057,291.290250
2022-03-21 11:42:00,41264.06,41282.03,41260.81,41282.03,0.312523,12901.578908
2022-03-21 11:43:00,41293.07,41296.17,41293.07,41293.53,0.484014,19986.628460
2022-03-21 11:44:00,41292.70,41292.70,41271.28,41282.43,0.010763,444.340133

In [3]:
sentiment_scores = pd.read_csv("/Users/alexzheng/Developer/GitHub/EC331-project/data/3.0/NEW_bitcoin_scores.csv",
                               index_col=0,
                               parse_dates=True)
sentiment_scores

                     weighted_sentiment_score
date
2021-02-05 10:53:00                  0.333760
2021-02-05 10:54:00                  0.000000
2021-02-05 10:55:00                  0.591740
2021-02-05 10:58:00                 -0.465576
2021-02-05 10:59:00                  0.457929
...                                       ...
2021-08-21 12:55:00                  0.330864
2021-08-21 12:56:00                  0.345120
2021-08-21 12:57:00                  0.183834
2021-08-21 12:58:00                  0.443081
2021-08-21 12:59:00                  0.465067

[85734 rows x 1 columns]

In [4]:
# Merge price and sentiment data
df = pd.merge(close_prices, sentiment_scores, on='date', how='outer')

# Select dates
df = df.loc['2021-02-05 10:53:00':'2021-08-21 12:59:00']

# Display first few rows
df.head()

,open,high,low,close,Volume BTC,Volume USD,weighted_sentiment_score
date,,,,,,,
2021-02-05 10:53:00,37446.89,37447.13,37415.68,37430.00,2.000066,74862.470380,0.33376
2021-02-05 10:54:00,37461.03,37463.49,37430.96,37430.96,2.878405,107741.474771,0.00000
2021-02-05 10:55:00,37440.64,37476.73,37440.64,37473.12,1.085219,40666.531696,0.59174
2021-02-05 10:56:00,37482.24,37488.05,37456.35,37488.05,0.444753,16672.908456,NaN
2021-02-05 10:57:00,37497.71,37499.73,37474.14,37478.90,0.594074,22265.252407,NaN

In [5]:
df.count()

open                        283807
high                        283807
low                         283807
close                       283807
Volume BTC                  283807
Volume USD                  283807
weighted_sentiment_score     85734
dtype: int64

In [6]:
print(f"The number of data missing: \n{df.isnull().sum()}")

The number of data missing:
open                             0
high                             0
low                              0
close                            0
Volume BTC                       0
Volume USD                       0
weighted_sentiment_score    198073
dtype: int64

In [7]:
# Forward-fill missing sentiment scores
df['weighted_sentiment_score'] = df['weighted_sentiment_score'].ffill()

In [8]:
df.head()

,open,high,low,close,Volume BTC,Volume USD,weighted_sentiment_score
date,,,,,,,
2021-02-05 10:53:00,37446.89,37447.13,37415.68,37430.00,2.000066,74862.470380,0.33376
2021-02-05 10:54:00,37461.03,37463.49,37430.96,37430.96,2.878405,107741.474771,0.00000
2021-02-05 10:55:00,37440.64,37476.73,37440.64,37473.12,1.085219,40666.531696,0.59174
2021-02-05 10:56:00,37482.24,37488.05,37456.35,37488.05,0.444753,16672.908456,0.59174
2021-02-05 10:57:00,37497.71,37499.73,37474.14,37478.90,0.594074,22265.252407,0.59174

In [9]:
df.isna().sum()

open                        0
high                        0
low                         0
close                       0
Volume BTC                  0
Volume USD                  0
weighted_sentiment_score    0
dtype: int64

In [10]:
df.to_csv("/Users/alexzheng/Developer/GitHub/EC331-project/data/3.0/Bitcoin_data_full.csv")